# Generated by Django 4.0.3 on 2022-04-01 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_rename_number_counter_cnumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counter',
            name='Cnumber',
        ),
    ]
