# Generated by Django 4.0.3 on 2022-04-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_random_link_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='random_link',
            name='counter',
        ),
    ]
