# Generated by Django 4.0.3 on 2022-04-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_remove_random_link_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='random_link',
            name='link',
            field=models.TextField(max_length=2300),
        ),
    ]
