# Generated by Django 4.0.3 on 2022-04-01 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_random_link_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='random_link',
            name='Counter',
            field=models.IntegerField(default=0),
        ),
    ]
