# Generated by Django 4.0.3 on 2022-04-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_random_link_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='random_link',
            name='id',
        ),
        migrations.AddField(
            model_name='random_link',
            name='auto_increment_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
