# Generated by Django 4.0.3 on 2022-04-01 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_random_link_id_random_link_auto_increment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='random_link',
            name='auto_increment_id',
            field=models.AutoField(default='', primary_key=True, serialize=False),
        ),
    ]
