# Generated by Django 4.0.3 on 2022-04-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_random_link_auto_increment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='random_link',
            name='auto_increment_id',
        ),
        migrations.AddField(
            model_name='random_link',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
