# Generated by Django 4.0.3 on 2022-04-01 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_id_random_link_counter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='random_link',
            old_name='Counter',
            new_name='auto_increment_id',
        ),
    ]
